#!/bin/sh

export MY_OS="macOS"
export BIN_PATH="$HOME/.local/share/lua-language-server/bin/$MY_OS/lua-language-server"
export OPTS="$HOME/.local/share/lua-language-server/main.lua"

$BIN_PATH -E $OPTS
